# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: colburn.
description: >- # this means to ignore newlines until "baseurl:"
  Doc site all things AI, Tech, and my personal experiments.
baseurl: "/bay" # the subpath of the site
url: "https://colburncodes.github.io" # the base hostname & protocol for the site
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: colburnsanders@gmail.com
      link: mailto:yourmail@domain.com
  follow:
    - name: Twitter
      link: https://twitter.com/whocolburn
      username: "@whocolburn"
    - name: LinkedIn
      link: http://linkedin.com/in/colburn-sanders
    - name: GitHub
      link: http://github.com/colburncodes
    - name: Dribbble
      link: https://dribbble.com/getcolburn


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
